services:
- docker
script:
- docker build -t wtanaka/ubuntu-1604-oracle-java-8 .
- >
  docker run wtanaka/ubuntu-1604-oracle-java-8 java -version
  2>&1 | grep "java version .1.8"
# Make sure it is still possible to use apt
- >
  docker run wtanaka/ubuntu-1604-oracle-java-8 sh -c "apt-get update && apt-get install less"
